version: '3.9'

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=mlmonitor
      - DOCKER_INFLUXDB_INIT_BUCKET=cpu_monitor
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped
    networks:
      - ml_internal

  ml-monitoring:
    build: .
    ports:
      - "8005:8000"  # Изменено: на хосте порт 8005, внутри контейнера 8000
    environment:
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_TOKEN: "my-super-secret-token"
      INFLUXDB_ORG: "mlmonitor"
      INFLUXDB_BUCKET: "cpu_monitor"
      # Теперь мы можем дотянуться до Prometheus из банковского проекта напрямую по имени контейнера!
      TEST_PROMETHEUS_URL: "http://banking-prometheus:9090"
      CPU_METRIC_NAME: "cpu_usage_percent"
      SCRAPE_INTERVAL_SEC: "15"
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - ml_internal
      - banking_network  # Подключаем к сети банковского проекта

  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3005:3000"  # Изменено: на хосте порт 3005, внутри контейнера 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_ORG: mlmonitor
      INFLUXDB_BUCKET: cpu_monitor
      INFLUXDB_TOKEN: my-super-secret-token
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - ml_internal

volumes:
  influxdb_data:
  grafana_data:

networks:
  ml_internal:  # Внутренняя сеть только для этого проекта (изоляция Influx и Grafana)
  banking_network:
    external: true
    # Укажите точное имя сети банковского проекта. 
    # Посмотреть его можно через команду: docker network ls
    name: docker_default
